# Generated by Django 2.1.1 on 2018-10-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonelist',
            name='createTime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='regTime',
            field=models.DateField(auto_now=True),
        ),
    ]
